frontend:
  std-module-sources: stdlib/std
  core-module-sources: stdlib/core
backends:
  noop:
    platform-sources: backend-api/src/main/emerge/noop-backend-platform
  x86_64-pc-linux-gnu:
    ffi-c-sources: llvm-backend/src/main/emerge-ffi-c
    libc-sources: llvm-backend/src/main/emerge-linux-libc
    platform-sources: llvm-backend/src/main/emerge-platform-linux
    llvm-installation-directory: /usr/lib/llvm-18
    static-libs:
      crtbeginS: /usr/lib/gcc/x86_64-linux-gnu/11/crtbeginS.o
      crtendS: /usr/lib/gcc/x86_64-linux-gnu/11/crtendS.o
      Scrt1: /lib/x86_64-linux-gnu/Scrt1.o
      libcSO: /usr/lib/x86_64-linux-gnu/libc.so.6
      libunwind: /home/tmarstaller/coding/tmarsteel/emerge-lang/local-resources/libunwind/lib/libunwind-x86_64.a