load("//:emerge_module.bzl", "emerge_module_internal")

emerge_module_internal(
    name = "emerge.core",
    visibility = ["//visibility:public"],
)

emerge_module_internal(
    name = "emerge.std",
    visibility = ["//visibility:public"],
)

emerge_module_internal(
    name = "emerge.platform",
    visibility = ["//visibility:public"],
)

emerge_module_internal(
    name = "emerge.ffi.c",
    visibility = ["//visibility:public"],
)
