name: build
run-name: Build & Test the entire project
on:
  - push
jobs:
  maven-build:
    runs-on: ubuntu-22.04
    name: maven build
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version-file: .java-version
          distribution: zulu
          cache: maven
      - name: mvn clean verify
        run: mvn -B clean verify
